//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakiye
    {
        public int Id { get; set; }
        public decimal Bakiye1 { get; set; }
        public Nullable<System.DateTime> SonBakiyeHesaplanmaTarihi { get; set; }
        public int HesapId { get; set; }
    
        public virtual Hesap Hesap { get; set; }
    }
}
