//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankaEntities : DbContext
    {
        public BankaEntities()
            : base("name=BankaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bakiye> Bakiyes { get; set; }
        public virtual DbSet<HareketTipleri> HareketTipleris { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<KullaniciTipleri> KullaniciTipleris { get; set; }
        public virtual DbSet<Hesap> Hesaps { get; set; }
        public virtual DbSet<HesapHareketleri> HesapHareketleris { get; set; }
    }
}
