//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HareketTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HareketTipleri()
        {
            this.HesapHareketleris = new HashSet<HesapHareketleri>();
        }
    
        public int Id { get; set; }
        public string HareketTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HesapHareketleri> HesapHareketleris { get; set; }
    }
}
