//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hesap()
        {
            this.Bakiyes = new HashSet<Bakiye>();
            this.HesapHareketleris = new HashSet<HesapHareketleri>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> HesapBaslangic { get; set; }
        public Nullable<System.DateTime> HesapBitis { get; set; }
        public int KullaniciId { get; set; }
        public string HesapAdi { get; set; }
        public decimal GonderilicekPara { get; set; }
        public int GonderilecekId { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<int> HesapTip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakiye> Bakiyes { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HesapHareketleri> HesapHareketleris { get; set; }
    }
}
