//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaOtomasyon.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Hesaps = new HashSet<Hesap>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string AdSoyad
        {
            get
            {
                return Ad + " " + Soyad;
            }
        }
        public string Email { get; set; }
        public string TcKimlik { get; set; }
        public long CepNo { get; set; }
        public Nullable<short> EvNo { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public int KullaniciTipi { get; set; }
        public string Sifre { get; set; }
    
        public virtual KullaniciTipleri KullaniciTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hesap> Hesaps { get; set; }
    }
}
